reviews:
  profile: "chill"  # Options: "chill", "assertive", or "pythonic"
  request_changes_workflow: false
  high_level_summary: true
  poem: false
  review_status: true

language: "en-US"

path_instructions:
  - path: "**/*.py"
    instructions: |
      - Review Python code for PEP 8 compliance
      - Check for security vulnerabilities
      - Suggest performance improvements
      - Validate error handling
